package View;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author anarvaezgo
 */
public class FrmVideoClub extends javax.swing.JFrame {

    /**
     * Creates new form FrmVideoClub
     */
    public FrmVideoClub() {
        initComponents();
        SpinnerNumberModel spinner = new SpinnerNumberModel();
        spinner.setMaximum(0);
        spinner.setMaximum(32);
        spnDays.setModel(spinner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panels = new javax.swing.JTabbedPane();
        PanelListProduct = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmovies = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVideoGames = new javax.swing.JTable();
        PanelAddProduct = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RbdMovie = new javax.swing.JRadioButton();
        RbdVideoGame = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtTittle1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spnDays = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        RbdYes = new javax.swing.JRadioButton();
        RbdNot = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelInformationVideogame = new javax.swing.JPanel();
        CmbStyle = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CmbPlatform = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelListProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblmovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblmovies);

        PanelListProduct.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 980, 150));

        tblVideoGames.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVideoGames);

        PanelListProduct.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 980, 160));

        panels.addTab("List Product", PanelListProduct);

        PanelAddProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rented :");
        PanelAddProduct.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 60, -1));
        PanelAddProduct.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, -1));

        jLabel2.setText("Rental Price :");
        PanelAddProduct.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        buttonGroup1.add(RbdMovie);
        RbdMovie.setText("Movie");
        PanelAddProduct.add(RbdMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        buttonGroup1.add(RbdVideoGame);
        RbdVideoGame.setText("Video Game");
        PanelAddProduct.add(RbdVideoGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel3.setText("Title : ");
        PanelAddProduct.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        PanelAddProduct.add(txtTittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, -1));

        jLabel4.setText("Rental Term :");
        PanelAddProduct.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        PanelAddProduct.add(spnDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, -1));

        jLabel5.setText("Type :");
        PanelAddProduct.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, -1));

        buttonGroup2.add(RbdYes);
        RbdYes.setText("Yes");
        PanelAddProduct.add(RbdYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, -1));

        buttonGroup2.add(RbdNot);
        RbdNot.setText("Not");
        PanelAddProduct.add(RbdNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(194, 73, 73));
        PanelAddProduct.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 790, 30));

        panelInformationVideogame.setBorder(javax.swing.BorderFactory.createTitledBorder("Information Video Games"));
        panelInformationVideogame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CmbStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select :", "Action", "Sports", "Adventure", "Puzzle", "Childish", " " }));
        panelInformationVideogame.add(CmbStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 170, -1));

        jLabel6.setText("Style :");
        panelInformationVideogame.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, -1));

        jLabel7.setText("Platform:");
        panelInformationVideogame.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 70, -1));

        CmbPlatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select :", "Xbox", "PlayStation", "Wii", " " }));
        panelInformationVideogame.add(CmbPlatform, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 170, -1));

        PanelAddProduct.add(panelInformationVideogame, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 560, 100));

        panels.addTab("Add Product", PanelAddProduct);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        panels.addTab("Product Tab", jPanel5);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        panels.addTab("List Client", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        panels.addTab("Add Client", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        panels.addTab("Client Tab", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        panels.addTab("Rental Product", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        panels.addTab("Consult Rent", jPanel11);

        getContentPane().add(panels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVideoClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVideoClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVideoClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVideoClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVideoClub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbPlatform;
    private javax.swing.JComboBox<String> CmbStyle;
    private javax.swing.JPanel PanelAddProduct;
    private javax.swing.JPanel PanelListProduct;
    private javax.swing.JRadioButton RbdMovie;
    private javax.swing.JRadioButton RbdNot;
    private javax.swing.JRadioButton RbdVideoGame;
    private javax.swing.JRadioButton RbdYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelInformationVideogame;
    private javax.swing.JTabbedPane panels;
    private javax.swing.JSpinner spnDays;
    private javax.swing.JTable tblVideoGames;
    private javax.swing.JTable tblmovies;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTittle1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox<String> getCmbPlatform() {
        return CmbPlatform;
    }

    public javax.swing.JComboBox<String> getCmbStyle() {
        return CmbStyle;
    }

    public javax.swing.JPanel getPanelAddProduct() {
        return PanelAddProduct;
    }

    public javax.swing.JPanel getPanelListProduct() {
        return PanelListProduct;
    }

    public javax.swing.JRadioButton getRbdMovie() {
        return RbdMovie;
    }

    public javax.swing.JRadioButton getRbdNot() {
        return RbdNot;
    }

    public javax.swing.JRadioButton getRbdVideoGame() {
        return RbdVideoGame;
    }

    public javax.swing.JRadioButton getRbdYes() {
        return RbdYes;
    }

    public javax.swing.JSpinner getSpnDays() {
        return spnDays;
    }

    public javax.swing.JTable getTblVideoGames() {
        return tblVideoGames;
    }

    public javax.swing.JTable getTblmovies() {
        return tblmovies;
    }

    public javax.swing.JTextField getTxtPrice() {
        return txtPrice;
    }

    public javax.swing.JTextField getTxtTittle1() {
        return txtTittle1;
    }

    public javax.swing.JTabbedPane getPanels() {
        return panels;
    }
}
